# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b7f25baeadaa5fd32a6ea005737aa8a"
application_url = "https://eight-encountered-permit-likely.trycloudflare.com"
embedded = true
name = "product-list-test"
handle = "product-list-test"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://eight-encountered-permit-likely.trycloudflare.com/auth/callback",
  "https://eight-encountered-permit-likely.trycloudflare.com/auth/shopify/callback",
  "https://eight-encountered-permit-likely.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
